version: "3.3"
services:
  wireguard:
    image: linuxserver/wireguard
    cap_add:
      - NET ADMIN
      - SYS_MODULE
    environment:
      - PUID= 1000
      - PGID= 1000
      - TZ= America/Mendoza
      - SERVERURL= 186.122.250.25
      - SERVERPORT= 51820
      - PEER= 2
      - PEERDNS= AUTO
      - INTERNAL_SUBNET= 10.13.13.0
    volumes:
      - /root/wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped